version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "chrisrohr"
      - "sleberknight"
    reviewers:
      - "chrisrohr"
      - "sleberknight"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "chrisrohr"
      - "sleberknight"
    reviewers:
      - "chrisrohr"
      - "sleberknight"
